# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tableViewActivities' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tableViewActivities

pod "SnapKit"
pod "SDWebImage"
pod "Alamofire"
pod "TableViewReloadAnimation"

  target 'tableViewActivitiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tableViewActivitiesUITests' do
    # Pods for testing
  end

end
